apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    {{- range $key, $val := .Values.podAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels: 
    {{- range $key, $val := .Values.podLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}